Added Query Implementation
KnowItAllAus/cube.js-korowa pull request #2
Opened 2024-03-14 05:45 UTC by enhanse

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[For example #12]

**Description of Changes Made (if issue reference is not provided)**

[Description goes here]

2024-03-18 00:50 UTC, timbrownls20 requested changes

2024-03-18 00:50 UTC, timbrownls20 commented on packages/cubejs-testing-shared/src/db/vertica.ts
> +      // .withEnv('VERTICA_MEMDEBUG', '2') // Required for ARM architecture
best to remove - or control with const or something. Legit probably for mac testing

2024-03-18 00:50 UTC, timbrownls20 commented on packages/cubejs-vertica-driver/src/VerticaQuery.js
> +      // TODO here can be measure type of string actually
remove TODO

2024-03-18 00:53 UTC, timbrownls20 reviewed
i think it's best to update the vertica driver and bring in the latest version of cubejs into this PR

2024-03-18 14:12 UTC, enhanse commented on packages/cubejs-testing-shared/src/db/vertica.ts
> +      // .withEnv('VERTICA_MEMDEBUG', '2') // Required for ARM architecture
Removed

2024-03-19 22:19 UTC, timbrownls20 approved these changes

2024-03-20 01:35 UTC, timbrownls20 approved these changes

2024-03-20 02:03 UTC, merged